---
- name: Skapa Redis-container
  hosts: all
  become: true
  tasks:
    - name: Skapa Redis-datakatalog
      file:
        path: /var/lib/redis
        state: directory
      environment:
        my_var: "{{ hostvars[inventory_hostname]['my_var'] | default('default_value') }}"

    - name: Skapa Redis-container
      docker_container:
        name: my_redis
        image: redis:latest
        state: started
        volumes:
          - /var/lib/redis:/data
        ports:
          - "6380:6379"
      environment:
        my_var: "{{ hostvars[inventory_hostname]['my_var'] | default('default_value') }}"
