version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - cluster.name=elastic-cluster
      - discovery.seed_hosts=elasticsearch  # Replace discovery.type with discovery.seed_hosts
    sysctls:
      - vm.max_map_count=262144
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
    networks:
      - elastic_network
