---
- name: Uppdatera Docker-container
  hosts: web_servers
  become: true
  tasks:
    - name: Stoppa Redis-container
      docker_container:
        name: my_redis_container
        image: redis:latest
        state: stopped

    - name: Ta bort Redis-container
      docker_container:
        name: my_redis_container
        image: redis:latest
        state: absent

    - name: Dra senaste Redis-bilden
      docker_image:
        name: redis:latest
        source: pull

    - name: Skapa Redis-container
      docker_container:
        name: my_redis_container
        image: redis:latest
        state: started
        restart_policy: always
        ports:
          - "6379:6379"
        volumes:
          - "/var/lib/redis/data:/data"
